// <auto-generated />
namespace Product.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class products : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(products));
        
        string IMigrationMetadata.Id
        {
            get { return "202001310249492_products"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
